# -*- coding: utf-8 -*-
"""Data science python complete 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-skdEfl5fboevPKAFookMoPzwgYvFuKN
"""

x=2
y=4
for i in range(x,y):# it means 2,4
    print(i)
    if i==3:
      pass
    elif i==4:
      break
    print(i)

x=4
y=10
while x>y:
  x=1
  y+=1
else:
  y=1
print(y)

x=3
y=6
if x<y:
  if y>10:
    z=x+y
  else:
    z=x-y
else:
  z=x*y
print(z)

x=5
y=3
if x<y:
  z=x+y
elif x>y:
  z=x-y
else:
  z=x+y
print(z)

x=4
y=8
for i in range(x,y):
  if i%2==0:
    pass
  else:
    print(i)

x=6
y=3
if x>y:
  z=x+y
elif x<y:
  z=x-y
else:
  z=x*y
print(z)

my_tupe=(1,2,3)
new_tupe=my_tupe+(4,5,6)
print(new_tupe)

my_tupe=(1,2,3)
new_tupe=my_tupe+(4,)
print(new_tupe)

my_tupe=(1,2,3,4,5)
sum_of_tupe=sum(my_tupe)
print(sum_of_tupe)

my_tupe=(1,2,3,4,5)
print(sum(my_tupe))

my_list=[1,2,3,4,5]
del my_list[3]
print(my_list)

my_list=[1,2,3,4,5]
my_list.remove(3)
print(my_list)

my_list=[1,2,3,4,5]
my_list.insert(2,10)
print(my_list)

my_list.sort(reverse=True)
print(my_list)

my_list.sort()
print(my_list)

my_tupe=(1,2,3,4,5)
new_tupe=my_tupe[-3:-1]
print(new_tupe)

my_list=[1,2,3,4,5]
repeated_list=my_list*2
print(repeated_list)

x=3
y=6
while x<y:
  if y%2==0:
    x+=y
  else:
    x=y
  print(x)

def count_vowels(word):
  vowels=['a','e','i','o','u']
  count=0
  for letter in word:
    if letter.lower()in vowels:
      count+=1
    results=count_vowels(word)
    print(results)

def calculate_average(numbers):
  return sum(numbers)/len(numbers)
my_num=[1,2,3,4,5]
result=calculate_average(my_num)
print(result)

def modify_list(ist):
  ist.append(4)
my_list=[1,2,3]
modify_list(my_list)
print(len(my_list))

for i in range (1,10,2):
  print(i)

names=['ravi','shankar','vishnu','vardhan','murari','paramesh']
for i in names:
  print(i)

"""For loop and while loop this are two types of loops we have in python"""

#accept user input for a number and caculate the summ of numbers between 1 and that user input
sum1=0
n=int(input('enter the value'))
for i in range(1,n+1,1):
  sum1+=i
print('\n')
print('sum is :sum1')

#print multpilicatuion table of any number given by the user
n=int(input('enter your value'))
for i in range(1,11,1):
  prod=n*i
  print(prod)

n=int(input('enter yor value'))
for i in range(1,11,1):
  no=n*i
  print(no)

list1=[23,55,90,35,78,120,470,45,95,112,83,27]
for value in list1:
  if (value%5==0):
    print(value)

#list reversable using loop
list2=[23,54,89,36,43,12,89,34]
start=len(list2)-1
stop=-1
step=-1
for i in range(start,stop,step):
  print(list2[i])

#Display -10 to -1 using the loop
for i in range(-10,0,1):
  print(i)

#indexing technique
list=[12,23,45,67,86,87,544,643,67,34]
for i in list:
  print(list[::-1])
  break

#write a program for displaying all prime numbers in  range
start=25
stop=120
print('prime numbers between',start,'and',stop,'are:')
for num in range (start,stop+1):
  if num>1:
    for i in range(2,num):
        if (num%i==0):
            break
    else:
         print(num)

#printing pattern examples
rows=5
for i in range (0,rows):
  for j in range(0,i+1):
    print('*',end=' ')
  print()
  print('\r')

#printing following patterns using loops
#5  4 3  2 1
#4 3 2 1
# 3 2 1
#1
n=5
k=5
for i in range(0,n+1):
   for j in range(k-i,-1,-1):
       print(j,end='')
  print()

#print the following patterns
print('Number Pattern')
latNumbe=6
for row in range(1,lastNumber):
   for column in range(1,row+1):
      print(column ,end =' ')
    print('')

# write a loop find the patterns of any number
num = int(input("Enter number whose factorial is needed"))
factorial = 1
if num < 0:
    print("Factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    for i in range(1, num + 1):
        factorial = factorial * i
    print("The factorial of", num, "is", factorial)

#Reverse a given integer number
num = int(input('Enter number whose reverse you need to calculate'))
reverse_number = 0
print("Given Number ", num)
while num > 0:
    reminder = num % 10
    reverse_number = (reverse_number * 10) + reminder
    num = num // 10
print("Revered Number ", reverse_number)

#Display the cube of the number up to a given integer
input_number = 12
for i in range(1, input_number + 1):
  print("Current Number is :", i, " and the cube is", (i * i * i))

#Find the sum of the series 2 +22 + 222 + 2222 + .. n terms
number_of_terms = 5
start = 2
sum = 0
for i in range(0, number_of_terms):
    print(start, end=" ")
    sum += start
    start = (start * 10) + 2
print("\nSum of above series is:", sum)